version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: hm2-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monHotelManagement
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  hotelmanagement2-backend:
    container_name: hm2-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/monHotelManagement?serverTimezone=Europe/Paris&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  hotelmanagement2-frontend:
    container_name: hm2-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  mysql_data:
